### ISSUE TITLE
Artículos sin resumen ni abstract 

### ISSUE THREAD

**Issue by irvcaza** [Isela-Saucedo/web_scraping#10]
Primeramente, felicitarte por el excelente trabajo en la carpeta 27-07-2022. Aunque tiene menos archivos los errores se redujeron drásticamente.

Estoy detectando que algunas entradas particulares no tienen ni abstract ni resumen. En particular 

- Revista15.03.csv 236 filas. 3 nulos 
- Revista25.csv 64 filas. 8 nulos 
- Revista21.02.csv 240 filas. 106 nulos 
- Revista15.02.csv 289 filas. 2 nulos 
- Revista15.04.csv 260 filas. 3 nulos 

Si revisamos Revista15.03.csv vemos que una de las entradas sin información es 

<html>
<body>

Titulo Revista | Area | Tematica | Titulo Articulo | Resumen | Abstract | Link Articulo | Link PDF
-- | -- | -- | -- | -- | -- | -- | --
Revista Mexicana de Ciencias Geológicas | I. Físico Matemáticas y Ciencias de la Tierra | Geociencias | Lower Permian brachiopods and trilobite from n... | NaN | NaN | http://rmcg.geociencias.unam.mx/index.php/rmcg... | http://rmcg.geociencias.unam.mx/index.php/rmcg...

</body>
</html>

la cual si tiene [abstract](http://rmcg.geociencias.unam.mx/index.php/rmcg/article/view/862). Revisando tu código, y el html creo que un `<p>` se metió en el camino 

`<p><strong>&nbsp;</strong></p>`

Habrá que revisarlo 

ME preocupa un poco mas la Revista21.02.csv que si tiene mas nulos. 
En este caso, tomando un ejemplo 

<html>
<body>

Titulo Revista | Area | Tematica | Titulo Articulo | Resumen | Abstract | Link Articulo | Link PDF
-- | -- | -- | -- | -- | -- | -- | --
Perfiles Latinoamericanos | V. Ciencias Sociales | Ciencia Política; Sociología; Economía, Políti... | Evaluación de la reforma del sistema de pensio... | NaN | NaN | https://perfilesla.flacso.edu.mx/index.php/per... | https://perfilesla.flacso.edu.mx/index.php/per...

</body>
</html>

también tiene [resumen ](https://perfilesla.flacso.edu.mx/index.php/perfilesla/article/view/153) pero no tiene las etiquetas que estableces en tu [código ](https://github.com/Isela-Saucedo/web_scraping/blob/9d261dd104ed22a20ed0c3be7d704c1754113d21/021.Perfiles%20Latinoamericanos.ipynb?short_path=37360d1#L196)

**Comment by Isela-Saucedo** [comment]
Modificado d6c8c5b1e4250d0b814e8a4c8bab89991e1d81c3

**Comment by irvcaza** [comment]
El commit que mencionas 

> Modificado [d6c8c5b](https://github.com/Isela-Saucedo/web_scraping/commit/d6c8c5b1e4250d0b814e8a4c8bab89991e1d81c3)

no hace referencia a los archivos que te comento (Revista15 y Revista21) Se hicieron cambios en estas o quedan para una siguiente iteración?
