### ISSUE TITLE
Revista 25 

### ISSUE THREAD

**Issue by irvcaza** [Isela-Saucedo/web_scraping#12]
El cuaderno [025.Anuario Mexicano de Derecho Internacional.ipynb](https://github.com/Isela-Saucedo/web_scraping/blob/7a689a8695b625c5bea6231b5e6cdcbeaae7d31e/025.Anuario%20Mexicano%20de%20Derecho%20Internacional.ipynb) no coincide con el archivo CSV correspondiente.

En el cuaderno se observan 22 artículos y en el CSV hay 64. Aun así, haciendo un revisión visual, conté al menos 76 artículos y estimo alrededor de 220.

No me puedo basar en tu código para encontrar el problema porque no se si ese sea con el que obtuviste los artículos.

**Comment by Isela-Saucedo** [comment]
La nueva versión esta en el titulo Revista025.ipynb con el issue: d6c8c5b1e4250d0b814e8a4c8bab89991e1d81c3
