### ISSUE TITLE
Revista 21

### ISSUE THREAD

**Issue by irvcaza** [Isela-Saucedo/web_scraping#13]
El cuaderno [021.Perfiles Latinoamericanos.ipynb](https://github.com/Isela-Saucedo/web_scraping/blob/7a689a8695b625c5bea6231b5e6cdcbeaae7d31e/021.Perfiles%20Latinoamericanos.ipynb) no coincide con su respectivo archivo CSV.

El cuaderno indica [8 artículos](https://github.com/Isela-Saucedo/web_scraping/blob/7a689a8695b625c5bea6231b5e6cdcbeaae7d31e/021.Perfiles%20Latinoamericanos.ipynb?short_path=37360d1#L363) mientras que los archivos CSV

- Revista21.01.csv 355 artículos
- Revista21.02.csv 240 artículos
- Revista21.03.csv 103 artículos

Quizá estoy interpretando mal los resultados. ¿Me podrías aclarar al respecto?

**Comment by Isela-Saucedo** [comment]
Buen dia, las revistas que llevan por título el nombre de la misma son las
que solo tomaban los volúmenes, por eso no coinciden, esas no son las
nuevas que se han modificado

**Comment by irvcaza** [comment]
>  esas no son las nuevas que se han modificado

Entiendo, ahora me queda mas claro. Ahora mi duda es ¿Cómo puedo identificar las que son de la nueva y de la vieja versión?

Yo esperaría que cuando publicas una actualización de las tablas también se actualiza el código. ¿Pero puede ser que no este viendo algo importante?

**Comment by Isela-Saucedo** [comment]
Esta es la nueva modificación 981f60fe0ff4a1f2eff959a6279d5835df6f540f
