### ISSUE TITLE
Duda acerca de la revista 057

### ISSUE THREAD

**Issue by Isela-Saucedo** [Isela-Saucedo/web_scraping#15]
En la segunda pagina en algunos volúmenes no hay artículos, pero por lo mismo al hacer la búsqueda de cuantos artículos hay marca error, ¿como se podría hacer para que aunque sean nulos algunos campos siga haciendo la búsqueda?
Es esta revista: 882973d4e04abacf31ea943afe65f2095922bb5a

**Comment by irvcaza** [comment]
Ejecuté la revista 57 y no pude encontrar el error. 

Creo que ya lo resolviste, si no es así, por favor házmelo saber.

Disculpa por no contestarte. No me había percatado de tu pregunta. Te recomiendo mencionarme con la arroba @, por ejemplo,  `@Isela-Saucedo` para que se me notifique. 

Mi recomendación inicial es usar try-except pero necesitaría revisar el caso particular. Si hay otra solución mas robusta
