### ISSUE TITLE
04-08-2022: Artículos faltantes en Revista27

### ISSUE THREAD

**Issue by irvcaza** [Isela-Saucedo/web_scraping#17]
Revisando el archivo Revista27.04.csv solo tiene un articulo, creo que la url que corresponde a este archivo es esta
https://myb.ojs.inecol.mx/index.php/myb/issue/archive/4
la cual contiene un solo [número](https://myb.ojs.inecol.mx/index.php/myb/issue/view/224). Sin embargo este número tiene varios artículos, no solo uno. 

No entiendo muy bien que estas haciendo en [027.Madera y Bosques.ipynb](https://github.com/Isela-Saucedo/web_scraping/blob/882973d4e04abacf31ea943afe65f2095922bb5a/027.Madera%20y%20Bosques.ipynb) parece incluso una versión anterior porque no tiene las columnas que habían acordado

**Comment by Isela-Saucedo** [comment]
Ya están corregidos esos archivos y se encuentran en la carpeta CSV en drive.
Como anteriormente se menciono las revistas que cuentan con el nombre completo son las anteriores, las que aun no se corregían. Las revistas completas son las que únicamente llevan por nombre Revista027.ipynb aquí donde se encuentra e8416f0db457a1bdbec66b01f64d8c05654f562b

**Comment by irvcaza** [comment]
> Las revistas completas son las que únicamente llevan por nombre Revista027.ipynb aquí donde se encuentra [e8416f0](https://github.com/Isela-Saucedo/web_scraping/commit/e8416f0db457a1bdbec66b01f64d8c05654f562b)

Ooooh de acuerdo me queda claro.

Entonces ya se podría proceder a eliminar los archivos originales conforme vas creando las nuevas versiones, si lo crees pertinente. 

Los nombres de los commits siguen siendo un poco crípticos "Codigo mejorado y completado" no nos dice mucho de que se cambió.
