### ISSUE TITLE
Faltan artículos en la revista 93

### ISSUE THREAD

**Issue by irvcaza** [Isela-Saucedo/web_scraping#18]
Revisando el archivo Revista093.03.csv  se encuentra que tiene 2 artículos. 

Sin embargo la [pagina](https://revistamexicanadeurologia.org.mx/index.php/rmu/issue/archive/3) que corresponde a este archivo tiene dos números. Cada uno con mas de 10 artículos. Al parecer hay una falla  al encontrar los links, muy posiblemente en esta [línea](https://github.com/Isela-Saucedo/web_scraping/blob/main/Revista093.ipynb?short_path=12700cd#L113) donde encuentra la primera sección pero hay otras secciones por escrapear.

**Comment by Isela-Saucedo** [comment]
Revista modificada.

**Comment by irvcaza** [comment]
De favor, podrías apuntar donde se hizo el cambio? Gracias
