### ISSUE TITLE
Resúmenes faltantes en Revista 61

### ISSUE THREAD

**Issue by irvcaza** [Isela-Saucedo/web_scraping#19]
Revisando el archivo Revista061.csv encuentro varias filas con Resumen y Abstract nulo, por ejemplo.  

Titulo Revista | Area | Tematica | Titulo Articulo | Resumen | Abstract | Link Articulo | Link PDF
-- | -- | -- | -- | -- | -- | -- | --
Investigación Económica | V. Ciencias Sociales | Teorías Económicas y su aplicación | EL EFECTO REBOTE DEL CONSUMO DE GAS NATURAL: E... | NaN | NaN | http://www.revistas.unam.mx/index.php/rie/arti... | http://www.revistas.unam.mx/index.php/rie/arti...
Investigación Económica | V. Ciencias Sociales | Teorías Económicas y su aplicación | A BRIEF NOTE ON PALLEY’S CRITICISM OF NEW DEVE... | NaN | NaN | http://www.revistas.unam.mx/index.php/rie/arti... | http://www.revistas.unam.mx/index.php/rie/arti...
Investigación Económica | V. Ciencias Sociales | Teorías Económicas y su aplicación | MORE ON THE LIMITS OF NEW DEVELOPMENTALISM | NaN | NaN | http://www.revistas.unam.mx/index.php/rie/arti... | http://www.revistas.unam.mx/index.php/rie/arti...
Investigación Económica | V. Ciencias Sociales | Teorías Económicas y su aplicación | IMPACT OF MEXICO’S SOCIAL PROGRAMS ON POVERTY | NaN | NaN | http://www.revistas.unam.mx/index.php/rie/arti... | http://www.revistas.unam.mx/index.php/rie/arti...
Investigación Económica | V. Ciencias Sociales | Teorías Económicas y su aplicación | IMPACT OF US ECONOMIC POLICY ON MAJOR LATIN AM... | NaN | NaN | http://www.revistas.unam.mx/index.php/rie/arti... | http://www.revistas.unam.mx/index.php/rie/arti...

Los cuales si tienen resumen y abstract. 

Comparando con artículos mas actuales, veo que hay un pequeño cambio en la estructura del `articleAbstract` que hace que que la búsqueda no sea adecuada en el [escrapeo](https://github.com/Isela-Saucedo/web_scraping/blob/fb671f2cc88d897e555f8e1569157cfd03f4cbea/Revista061.ipynb?short_path=93abea4#L661). Habrá que tomar en cuenta ambos casos o una aproximación mas generalizada. 

Además, noto que estos artículos tienen Resumen y Abstract, pero en el mejor de los casos solo se escrapea uno. Seria deseable tener ambos.

**Comment by irvcaza** [comment]
@Isela-Saucedo hay algún avance respecto a esto?

**Comment by Isela-Saucedo** [comment]
@irvcaza aquí esta el código con el que tengo problemas acerca del resumen y abstract 2c71221b58894dd94da161883ba9608bc7cd07ee

**Comment by irvcaza** [comment]
Revisando los artículos encuentro uno en particular que da el error que mencionas 
http://www.revistas.unam.mx/index.php/rie/article/view/82246
podemos que el abstract es el primer párrafo y el resumen es el segundo. Sin embargo, ambos tiene de titulo `Resumen` obviamente esto es un error pero las herramientas para detectar esto están fuera de este proyecto. Por lo que recomendaría omitir el abstract en este tipo de casos 

Te comparto el codigo

```
    #resumen
    try:
        resu=s_item.find('div', id='articleAbstract').text.lower().split("resumen")[1].strip()
        content_book['Resumen']=resu.replace("resumen","")
    except AttributeError:
        content_book['Resumen']=None
    except IndexError:
        content_book['Resumen']=None
    #abstract
    try:
        abst=s_item.find('div', id='articleAbstract').text.lower().split("abstract")[1].strip()
        content_book['Abstract']=abst.replace("abstract","")
    except AttributeError:
        content_book['Abstract']=None
    except IndexError:
        content_book['Abstract']=None
```

**Comment by Isela-Saucedo** [comment]
@irvcaza Funciona pero de igual forma toma el mismo texto en ambas columnas

**Comment by irvcaza** [comment]
Me podrías dar un ejemplo en particular? Cuando yo ejecuté el código obtuve una tabla así

 Titulo Revista | Area | Tematica | Titulo Articulo | Resumen | Abstract | Link Articulo | Link PDF
-- | -- | -- | -- | -- | -- | -- | --
Investigación Económica | V. Ciencias Sociales | Teorías Económicas y su aplicación | THE LONG RECESSION AND ECONOMIC CONSEQUENCES O... | en este artículo argumentamos que la tasa de g... | in this article, we argue the rate of profit i... | http://www.revistas.unam.mx/index.php/rie/arti... | http://www.revistas.unam.mx/index.php/rie/arti...
Investigación Económica | V. Ciencias Sociales | Teorías Económicas y su aplicación | THE GREEK CRISIS IN RETROSPECT: THE RATE OF PR... | la economía de grecia está en crisis desde el ... | the greek economy is in crisis since the fourt... | http://www.revistas.unam.mx/index.php/rie/arti... | http://www.revistas.unam.mx/index.php/rie/arti...
Investigación Económica | V. Ciencias Sociales | Teorías Económicas y su aplicación | REDISTRIBUTION, INEQUALITY, AND GROWTH: GVAR A... | en este artículo se investiga con un modelo gv... | this article investigates the effect of gdp re... | http://www.revistas.unam.mx/index.php/rie/arti... | http://www.revistas.unam.mx/index.php/rie/arti...
Investigación Económica | V. Ciencias Sociales | Teorías Económicas y su aplicación | TRADE AGREEMENT AND TRADE SPECIALIZATION BETWE... | el estudio analiza la relevancia del acuerdo c... | the study analyses the relevance of the trade ... | http://www.revistas.unam.mx/index.php/rie/arti... | http://www.revistas.unam.mx/index.php/rie/arti...
Investigación Económica | V. Ciencias Sociales | Teorías Económicas y su aplicación | LA INVERSIÓN EXTRANJERA DIRECTA EN MÉXICO: ANÁ... | en este artículo se presenta un estudio empíri... | an empirical study of foreign direct investmen... | http://www.revistas.unam.mx/index.php/rie/arti... | http://www.revistas.unam.mx/index.php/rie/arti...
... | ... | ... | ... | ... | ... | ... | ...
Investigación Económica | V. Ciencias Sociales | Teorías Económicas y su aplicación | AUTONOMÍA DEL BANCO DE MÉXICO, CRECIMIENTO Y D... | en agosto 1993 se otorgó autonomía al banco de... | on august 1993 the banco de méxico was granted... | http://www.revistas.unam.mx/index.php/rie/arti... | http://www.revistas.unam.mx/index.php/rie/arti...
Investigación Económica | V. Ciencias Sociales | Teorías Económicas y su aplicación | AUTONOMÍA DEL BANCO DE MÉXICO Y ESTABILIDAD MA... | analizamos la política monetaria que ha instru... | in this paper the banco de méxico’s monetary p... | http://www.revistas.unam.mx/index.php/rie/arti... | http://www.revistas.unam.mx/index.php/rie/arti...
Investigación Económica | V. Ciencias Sociales | Teorías Económicas y su aplicación | CONSIDERACIONES SOBRE POLÍTICA FISCAL Y EXPECT... | este documento estima para méxico el modelo de... | this document estimates the model of sargent, ... | http://www.revistas.unam.mx/index.php/rie/arti... | http://www.revistas.unam.mx/index.php/rie/arti...
Investigación Económica | V. Ciencias Sociales | Teorías Económicas y su aplicación | DÉFICIT FISCAL, CRECIMIENTO ECONÓMICO E INFLAC... | en este artículo analizamos la relación entre ... | this paper deals with the relationship between... | http://www.revistas.unam.mx/index.php/rie/arti... | http://www.revistas.unam.mx/index.php/rie/arti...
Investigación Económica | V. Ciencias Sociales | Teorías Económicas y su aplicación | LA ECONOMÍA POLÍTICA DE LA AUTONOMÍA DEL BANCO... | el propósito de este trabajo es indagar la lóg... | based on the classical political economy’s the... | http://www.revistas.unam.mx/index.php/rie/arti... | http://www.revistas.unam.mx/index.php/rie/arti...

por supuesto el resumen y abstract son lo mismo pero traducidos. Hay algunos artículos que tienen resumen 2 veces pero esto no puede resolverse ya que es un error de la pagina

**Comment by Isela-Saucedo** [comment]
Revista completada 6e61e58c92e58c41dbdbd835aa0a722bd5be7cc8

**Comment by Isela-Saucedo** [comment]
Así es como me sale la tabla al ejecutarlo como me dijiste, no pude subir
el archivo a la carpeta porque tengo problemas con el espacio
[image: image.png]

**Comment by irvcaza** [comment]
No me aparece la imagen
