### ISSUE TITLE
Convertir Instalacion.ipynb a requirements.txt

### ISSUE THREAD

**Issue by irvcaza** [Isela-Saucedo/web_scraping#2]
El uso de [Instalacion.ipynb](https://github.com/Isela-Saucedo/web_scraping/blob/7c38194319245b5bd6921a7efae08cc34e628537/Instalacion.ipynb) es excelente para saber que librerías utilizamos. 

La aproximación estándar es crear un archivo requirements el cual contiene todas las librerías necesarias (y opcionalmente sus versiones).

Puedes crearlo con `pip freeze > requirements.txt`

 te agrego una liga que da mas información acerca de este archivo 

https://learnpython.com/blog/python-requirements-file/

**Comment by Isela-Saucedo** [comment]
Modificado 17bb7cf5f78b64220ce65d75e447017af526dc5c

**Comment by irvcaza** [comment]
Hay algunos cambios propuestos en el comentario siguiente 
https://github.com/Isela-Saucedo/web_scraping/commit/17bb7cf5f78b64220ce65d75e447017af526dc5c#commitcomment-79556752
