### ISSUE TITLE
Link articulo incorrecto en revista 5 

### ISSUE THREAD

**Issue by irvcaza** [Isela-Saucedo/web_scraping#20]
Revisando el archivo Revista005.csv en la columna de Link Articulo en lugar de mostrar el enlace correspondiente al articulo, todos muestran una lista de URLs. Esto es un problema al formar la tabla donde en la linea 
[ `    url=vol2`](https://github.com/Isela-Saucedo/web_scraping/blob/fb671f2cc88d897e555f8e1569157cfd03f4cbea/Revista005.ipynb?short_path=05509a9#L155)
Donde reasignas el valor de url

**Comment by Isela-Saucedo** [comment]
Ya se modifico el link del articulo 6bb98b6e0124b126a72f0ac4983f74d83f2d4878 y la tabla quedo actualizada en la carpeta CSV
