### ISSUE TITLE
Eliminar Artículos  Presentación de revista 7

### ISSUE THREAD

**Issue by irvcaza** [Isela-Saucedo/web_scraping#21]
En el archivo Revista007.02.csv encontré dos artículos cuyo titulo es `Presentación`. Al revisarlos estos no se refieren a alguna publicación sino a la presentación de esos números en particular. 

Haciendo una revisión se encontraron los artículos 

Titulo Revista | Area | Tematica | Titulo Articulo | Resumen | Abstract | Link Articulo | Link PDF
-- | -- | -- | -- | -- | -- | -- | --
América Latina en la Historia Económica | IV. Humanidades y Ciencias de la Conducta | Historia Económica | Presentación | Los avances alcanzados desde hace varios decen... | NaN | http://alhe.mora.edu.mx/index.php/ALHE/article... | http://alhe.mora.edu.mx/index.php/ALHE/article...
América Latina en la Historia Económica | IV. Humanidades y Ciencias de la Conducta | Historia Económica | Presentación | El número que en esta ocasión presentamos deAm... | NaN | http://alhe.mora.edu.mx/index.php/ALHE/article... | http://alhe.mora.edu.mx/index.php/ALHE/article...
América Latina en la Historia Económica | IV. Humanidades y Ciencias de la Conducta | Historia Económica | Puertos. Presentación | La sección temática de este número está dedica... | NaN | http://alhe.mora.edu.mx/index.php/ALHE/article... | http://alhe.mora.edu.mx/index.php/ALHE/article...
América Latina en la Historia Económica | IV. Humanidades y Ciencias de la Conducta | Historia Económica | Consulados y comercio. Presentación | NaN | NaN | http://alhe.mora.edu.mx/index.php/ALHE/article... | http://alhe.mora.edu.mx/index.php/ALHE/article...

los cuales no deben estar en el CSV.

Te recomiendo usar algo como 

```
df_catalogo[
    ~ df_catalogo['Titulo Articulo'].str.contains("presentación", flags=re.IGNORECASE, na = False)
]
```
lo cual quiere decir: de la tabla `df_catalogo`, selecciona las filas que en la columna `Titulo Articulo` **NO** contenga el texto `presentación`

**Comment by Isela-Saucedo** [comment]
Revista modificada 1993cfbcc9b48f19dda1a9ec447283a1ad92f4ab

**Comment by irvcaza** [comment]
No encontré donde se realizó el cambio. Podrías indicarme?
