### ISSUE TITLE
Artículos faltantes en Revista143

### ISSUE THREAD

**Issue by irvcaza** [Isela-Saucedo/web_scraping#22]
Comparando el archivo Revista143.02.csv con la pagina http://dianoia.filosoficas.unam.mx/index.php/dianoia/issue/archive?issuesPage=2#issues encuentro que hay algunos artículos que no aparecen. Por ejemplo [Principios lógicos y principios morales: la identidad de los indiscernibles](http://dianoia.filosoficas.unam.mx/index.php/dianoia/article/view/406). Una causa muy probable es que cuando obtienes los números solo tomas el primero de cada año (nota que 2004 tiene 2) . En la línea a continuación vemos que haces un find en lugar de un findAll
https://github.com/Isela-Saucedo/web_scraping/blob/dbd8d4126a1b3ec129f90a1bcae92a34a7127022/Revista143.ipynb?short_path=f6f6c57#L76

**Comment by Isela-Saucedo** [comment]
Modificado 75debc2ab528e8d3f892aa436bea7c1fe3bba6ee
