### ISSUE TITLE
Probemas de estructura en revista 019

### ISSUE THREAD

**Issue by apimentela** [Isela-Saucedo/web_scraping#23]
Las revistas 019.14 y 019.15 tienen problemas con las columnas, algunos renglones tienen muchísimos elementos, parece un problema de parseo.

En la revista 019.14 detecté un problema ese problema en los renglones 48-49, el link del artículo que se reporta es:

http://www.revistagastroenterologiamexico.org/es-consenso-mexicano-sobre-el-uso-articulo-X0375090609477379

En la revista 019.15 ocurre en los renglones 5-6, con link:

http://www.revistagastroenterologiamexico.org/es-conceptos-actuales-acerca-del-tratamiento-articulo-X0375090608497851

**Comment by Isela-Saucedo** [comment]
Artículos modificados 6c102fab447959fd5e20d772772ff7baebfcdc5f
