### ISSUE TITLE
Error en resúmenes  del la Revista019

### ISSUE THREAD

**Issue by irvcaza** [Isela-Saucedo/web_scraping#25]
Revisando los archivos `Revista019.11.csv, Revista019.12.csv, Revista019.14.csv` encuentro resúmenes del tipo 

```
?? Introducción 
�� Introducción
¿ Introducción
```

Revisando los artículos originales encuentro resúmenes **Y** abstracts completos. Por lo que sospecho que se está recabando el resumen de manera incorrecta. 
Si puedes observar, esto solo se observa algunas páginas por lo que sospecho que el formato pudiera haber cambiado.

**Comment by Isela-Saucedo** [comment]
@irvcaza Hola, si note que se encuentran ambos idiomas en el resumen pero las etiquetas tienen el mismo nombre, ¿como puedo hacer para que tome una en cada idioma?

**Comment by irvcaza** [comment]
Hay varios planes de acción 
1. Hay que revisar si tienen el mismo orden, es decir. Siempre esta el resumen y después el abstract (o viceversa). Puedes entonces usar algunas propiedades de Beautiful Soup como [.children](https://beautiful-soup.readthedocs.io/en/latest/#contents-and-children)
2. Si a veces es primero el abstract y a veces resumen tienes que hacer una revisión mas detallada, tendrás que parar por todos los hijos de la etiqueta que contiene todo y cuando encuentres la palabra clave (`resumen` o `abstract`) entonces sabrás a que pertenece la siguiente etiqueta. Puedes usar algo como [.next_sibling](https://beautiful-soup.readthedocs.io/en/latest/#next-sibling-and-previous-sibling) 

Espero te sea de ayuda, si sigues teniendo problemas me dices para verlo mas a detalle.

**Comment by Isela-Saucedo** [comment]
@irvcaza Ya lo intente de varias maneras y no da el texto en ambos campos, de hecho lo intente con el mismo codigo que me diste de la revista 61

**Comment by Isela-Saucedo** [comment]
@irvcaza la mayoria de los articulos no resumen y abstract, lo que si tienen en comun es el texto completo 
¿Pongo el texto completo o mejor dejo nulo lo de abstract y resumen?

**Comment by irvcaza** [comment]
Puedes pasar enlaces de algunos ejemplos de esto? Para analizar mas a detalle
