### ISSUE TITLE
Duda de la Revista035

### ISSUE THREAD

**Issue by Isela-Saucedo** [Isela-Saucedo/web_scraping#26]
Tengo una duda ya que el resumen no esta en una etiqueta concisa, solo se encuentra dentro de una 'p', al querer tomarla no arroja nada. ¿Como podría tomar esa parte?3b1598877d73a4e390a96212886025334c5ae62e

**Comment by irvcaza** [comment]
Podrías poner el caso particular para revisarlo? Depende del caso es como se podría atacar esto.
El primer paso seria reducir a la etiqueta que contiene el `<p>`, es decir un nivel mas arriba. Una vez hecho esto

- Si es la única etiqueta `<p>` entonces puedes seguir usando `.find("p")`
- Si hay otras etiquetas `<p>` con texto que no quieres entonces puedes usar [.children](https://beautiful-soup.readthedocs.io/en/latest/#contents-and-children)

Una vez que vemos el ejemplo concreto podemos generar un (pseudo)código

**Comment by Isela-Saucedo** [comment]
Resuelto 30ce39a8e95f63383ddc4194f535b802a10adbec
