### ISSUE TITLE
Articulos editoriales en Revista023

### ISSUE THREAD

**Issue by irvcaza** [Isela-Saucedo/web_scraping#27]
Revisando el archivo Revista023.01.csv encuentro varios artículos con titulo repetido 'Editorial' . Algunos tienen abstract, algunos solo es Editorial. Es mejor omitir estos artículos

**Comment by Isela-Saucedo** [comment]
Ya están las correcciones en los csv.

**Comment by irvcaza** [comment]
Cambiaste el código? Hiciste algún commit?

**Comment by Isela-Saucedo** [comment]
Solo quite los titulos que no debian estar d169b9adedeb7e5271d2818657965bc6a004177e

**Comment by irvcaza** [comment]
@Isela-Saucedo  No hagas drop de index cuando este es creado automáticamente. 
Si por alguna razón cambia el orden, o cuando se agreguen artículos se eliminaran registros que no son. 
Mejor busca los artículos que tengan título 'Editorial'
