### ISSUE TITLE
Propuesta revista medigraphic

### ISSUE THREAD

**Issue by irvcaza** [Isela-Saucedo/web_scraping#28]
Referente al enlace compartido en la sesion 
https://www.medigraphic.com/cgi-bin/new/resumen.cgi?IDARTICULO=6464

Ciertamente el contenido de esta revista es un caos, va a ser muy complicado guiarnos por las etiquetas. Uno de los (semi)patrones que encontré fue por el texto. El resumen esta entre la palabra `RESUMEN` (o `FRAGMENTO`) y la palabra `REFERENCIAS` por lo que se puede hacer algo como esto 

```
r = requests.get("https://www.medigraphic.com/cgi-bin/new/resumen.cgi?IDARTICULO=6204")
soup = BeautifulSoup(r.text, 'html.parser')
box1 = soup.find('div', style='margin-top:35px;')
box1.text.split("RESUMEN")[1].split("REFERENCIAS")[0].strip()
```

Lo que hace esta ultima linea es tomar todo el texto y separarlo en dos partes por la palabra `RESUMEN`, toma la segunda parte (el texto después de `RESUMEN`). Ese texto lo vuelve a separar por la palabra `REFERENCIAS` y toma la primera parte (el texto antes de `REFERENCIAS`).

Es necesario agregar el caso cuando dice `FRAGMENTO`. No tuve oportunidad de probarlo con todos los artículos. Si pudieras hacer la prueba y me comentas en que artículos no funcionó

**Comment by Isela-Saucedo** [comment]
Ya lo intente de varias formas pero no toma la parte que esta en resumen o fragmento, tome toda la etiqueta para ver si con ella salia el texto pero no, no toma esas partes.

**Comment by irvcaza** [comment]
Puedes subir el código que tienes para ver como lo podemos desarrollar

**Comment by Isela-Saucedo** [comment]
Ya esta completada 30ce39a8e95f63383ddc4194f535b802a10adbec
