### ISSUE TITLE
Títulos en Revista019 

### ISSUE THREAD

**Issue by irvcaza** [Isela-Saucedo/web_scraping#29]
Revisando el archivo Revista019.14.csv detecté un par de artículos donde el titulo no coincide con la pagina web 

Titulo Revista | Area | Tematica | Titulo Articulo | Resumen | Abstract | Link Articulo | Link PDF
 -- | -- | -- | -- | -- | -- | -- | --
Revista de Gastroenterología de México | III. Medicina y Ciencias de la Salud | Gastroenterología | Tratamiento | Coordinador general:Dr. Ricardo Raña GaribayCo... | NaN | http://www.revistagastroenterologiamexico.org/... | http://www.revistagastroenterologiamexico.org/...
Revista de Gastroenterología de México | III. Medicina y Ciencias de la Salud | Gastroenterología | Tratamiento | ¿Cuál debe ser el objetivo del tratamiento del... | NaN | http://www.revistagastroenterologiamexico.org/... | http://www.revistagastroenterologiamexico.org/...

http://www.revistagastroenterologiamexico.org/es-guias-clinicas-diagnostico-tratamiento-enfermedad-articulo-X0375090609499116
http://www.revistagastroenterologiamexico.org/es-guias-clinicas-diagnostico-tratamiento-gastroenterologia-articulo-X0375090609496984

Viendo el código no veo las razones por lo que esto suceda.

https://github.com/Isela-Saucedo/web_scraping/blob/32d58766207a15c8967aa60caeeb6b06c9a2acc4/Revista019.ipynb?short_path=6e20786#L300

 Quizá se realizó con una versión anterior.

**Comment by irvcaza** [comment]
También sucede con los registros 68 y 71. 


http://www.revistagastroenterologiamexico.org/es-guias-clinicas-diagnostico-tratamiento-enfermedad-articulo-X0375090609499093
http://www.revistagastroenterologiamexico.org/es-guias-clinicas-diagnostico-tratamiento-encefalopatia-articulo-X0375090609499124

**Comment by Isela-Saucedo** [comment]
Listo, ya están correctos los titulos https://drive.google.com/file/d/1D9dAokVbmm9Y5LPUiFN-RivZrrcp8pVy/view?usp=sharing

**Comment by irvcaza** [comment]
Que se hizo para solucionarlo?

**Comment by irvcaza** [comment]
> Listo, ya están correctos los titulos https://drive.google.com/file/d/1D9dAokVbmm9Y5LPUiFN-RivZrrcp8pVy/view?usp=sharing

Podridas subirlo a la carpeta compartida de CSV? También revisar otros archivos de la misma revista

**Comment by Isela-Saucedo** [comment]
todo esta en la carpeta compartida y aqui esta el codigo 6c102fab447959fd5e20d772772ff7baebfcdc5f
