### ISSUE TITLE
Revista121 no tiene las columnas estándar 

### ISSUE THREAD

**Issue by irvcaza** [Isela-Saucedo/web_scraping#30]
Los archivos `Revista121.01.csv`, `Revista121.02.csv` y `Revista121.03.csv` tienen las columnas 
'Titulo de revista', 'Área', 'Temática', **'Titulo del libro'**, 'Resumen','Abstract', 'Link inicial', 'Link articulo'
Lo cual no cumple con el estándar. El problema esta en la siguiente línea

https://github.com/Isela-Saucedo/web_scraping/blob/44810a031f0a6e9420bc3a16e66b086a8a654adf/Revista121.ipynb?short_path=cab05d2#L177

**Comment by Isela-Saucedo** [comment]
Modificado de37b66e8b6e76420ae7d2394b3764d88190bbf5
