### ISSUE TITLE
Links incorrectos en Revista065 

### ISSUE THREAD

**Issue by irvcaza** [Isela-Saucedo/web_scraping#31]
En el archivo Revista065.01.csv todos los elementos de `Link Articulo` son iguales con el valor `http://www.gestionypoliticapublica.cide.edu/` 

Revisando el código veo que en la siguiente línea reemplazas el valor de url que recibe la función  

https://github.com/Isela-Saucedo/web_scraping/blob/c41cc0eceebab1b8bef502597c22c81eda9424b1/Revista065.ipynb?short_path=9816471#L238

**Comment by Isela-Saucedo** [comment]
Modificado, no había quitado la linea donde declaraba el link c85f391df03fa48d6cfa2f2974b1e19c4173c0d7
