### ISSUE TITLE
Eliminar resúmenes en Revista073

### ISSUE THREAD

**Issue by irvcaza** [Isela-Saucedo/web_scraping#32]
En el archivo Revista073.05.csv encuentro los siguientes registros 

 Titulo Revista | Area | Tematica | Titulo Articulo | Resumen | Abstract | Link Articulo | Link PDF
 -- | -- | -- | -- | -- | -- | -- | --
Revista Mexicana de Ingeniería Biomédica | VII. Ingenierías | Ciencias de la Salud | Self calibration of a telemetry system | No contiene resumen | NaN | http://www.rmib.mx/index.php/rmib/article/view... | http://www.rmib.mx/index.php/rmib/article/view...
Revista Mexicana de Ingeniería Biomédica | VII. Ingenierías | Ciencias de la Salud | Proportional temperature control for fermentat... | No contiene resumen | NaN | http://www.rmib.mx/index.php/rmib/article/view... | http://www.rmib.mx/index.php/rmib/article/view...
Revista Mexicana de Ingeniería Biomédica | VII. Ingenierías | Ciencias de la Salud | Development of a multilevel digitizer of telev... | No contiene resumen | NaN | http://www.rmib.mx/index.php/rmib/article/view... | http://www.rmib.mx/index.php/rmib/article/view...
Revista Mexicana de Ingeniería Biomédica | VII. Ingenierías | Ciencias de la Salud | Esfigmotacometro | No contiene resumen | NaN | http://www.rmib.mx/index.php/rmib/article/view... | http://www.rmib.mx/index.php/rmib/article/view...
Revista Mexicana de Ingeniería Biomédica | VII. Ingenierías | Ciencias de la Salud | Fijador de límites y detector de extralimentac... | No contiene resumen | NaN | http://www.rmib.mx/index.php/rmib/article/view... | http://www.rmib.mx/index.php/rmib/article/view...
Revista Mexicana de Ingeniería Biomédica | VII. Ingenierías | Ciencias de la Salud | Identificación de parámetros, un programa para... | No contiene resumen | NaN | http://www.rmib.mx/index.php/rmib/article/view... | http://www.rmib.mx/index.php/rmib/article/view...
Revista Mexicana de Ingeniería Biomédica | VII. Ingenierías | Ciencias de la Salud | Sistema de retención de imagen para fisiomonit... | No contiene resumen | NaN | http://www.rmib.mx/index.php/rmib/article/view... | http://www.rmib.mx/index.php/rmib/article/view...
Revista Mexicana de Ingeniería Biomédica | VII. Ingenierías | Ciencias de la Salud | Invitation for the eighth National Congress of... | No contiene resumen | NaN | http://www.rmib.mx/index.php/rmib/article/view... | http://www.rmib.mx/index.php/rmib/article/view...
Revista Mexicana de Ingeniería Biomédica | VII. Ingenierías | Ciencias de la Salud | Pérdida de un amigo | No contiene resumen | NaN | http://www.rmib.mx/index.php/rmib/article/view... | http://www.rmib.mx/index.php/rmib/article/view...
Revista Mexicana de Ingeniería Biomédica | VII. Ingenierías | Ciencias de la Salud | New board of directors of the SOMIB | No contiene resumen | NaN | http://www.rmib.mx/index.php/rmib/article/view... | http://www.rmib.mx/index.php/rmib/article/view...

Como puedes ver su `Resumen` es `No contiene resumen` por lo cual debería ser vacío. Hay que detectarlos y reemplazarlos

**Comment by Isela-Saucedo** [comment]
Modificado 3a5c1cba55c37340de62ed4ca53c7af8c1acf8e8
