### ISSUE TITLE
Columnas en revista 091

### ISSUE THREAD

**Issue by apimentela** [Isela-Saucedo/web_scraping#33]
Los títulos de las columnas en la revista 091 son diferentes a las demás.
parece que la diferencia está en la columna "Area"

**Comment by irvcaza** [comment]
Las diferencias son en varias columnas. Además de `Área`, también es `Temática` (con acento). Y también las columnas `Link inicial` y `Link articulo`

**Comment by Isela-Saucedo** [comment]
Modificado 9b03a55047c17372286dd78fd30d326addb59aa2
