### ISSUE TITLE
Resúmenes faltantes en Revista099

### ISSUE THREAD

**Issue by irvcaza** [Isela-Saucedo/web_scraping#34]
Revisando el archivo Revista099.01.csv, encuentro que ninguno tiene resumen ni abstract 

 Titulo Revista | Area | Tematica | Titulo Articulo | Resumen | Abstract | Link Articulo | Link PDF
 -- | -- | -- | -- | -- | -- | -- | --
Revista Mexicana de Angiología | III. Medicina y Ciencias de la Salud | Medicina | Infecciones de injertos vasculares por gramneg... | NaN | NaN | https://www.rmangiologia.com/frame_esp.php?id=79 | https://www.rmangiologia.com/files/rma_22_50_2...
Revista Mexicana de Angiología | III. Medicina y Ciencias de la Salud | Medicina | Reparación de trauma vascular femoral secundar... | NaN | NaN | https://www.rmangiologia.com/frame_esp.php?id=80 | https://www.rmangiologia.com/files/rma_22_50_2...
Revista Mexicana de Angiología | III. Medicina y Ciencias de la Salud | Medicina | Frecuencia de trombosis arteriales y venosas d... | NaN | NaN | https://www.rmangiologia.com/frame_esp.php?id=81 | https://www.rmangiologia.com/files/rma_22_50_2...
Revista Mexicana de Angiología | III. Medicina y Ciencias de la Salud | Medicina | Tumor del cuerpo carotídeo Shamblin III en pac... | NaN | NaN | https://www.rmangiologia.com/frame_esp.php?id=82 | https://www.rmangiologia.com/files/rma_22_50_2...
Revista Mexicana de Angiología | III. Medicina y Ciencias de la Salud | Medicina | Manejo multidisciplinario de leiomiosarcoma de... | NaN | NaN | https://www.rmangiologia.com/frame_esp.php?id=83 | https://www.rmangiologia.com/files/rma_22_50_2...

Sin embargo, revisando las paginas, estas si cuentan con resumen **Y** abstract. Por lo que habrá que revisar porque no se están captando. Revisando el código fuente de la página,  veo que las etiquetas que contienen esto no tienen algún identificador, por lo que una sugerencia seria usar todo el texto de `<history>` y separar por las palabras claves usando split. 

Esto se repite en los demás archivos de la Revista099

**Comment by Isela-Saucedo** [comment]
@irvcaza Ya vi que no toma el resumen porque el codigo no se encuentra en una sola seccion, las etiquetas del resumen estan fuera del codigo fuente y al tomar la que esta en el marco no lo muestra en la el data frame

**Comment by irvcaza** [comment]
Ya que son varios problemas de este tipo en distintas revistas, creo que lo mas adecuado es generar una sesión para resolver este tipo de problemas juntos.

Por favor genera un listado de las revistas que tienen este tipo de problema para escrapear para verlas una a una. Generamos una reunión extraordinaria la próxima semana

**Comment by Isela-Saucedo** [comment]
No se pudo extraer el resumen
