### ISSUE TITLE
Artículos de presentación en Revista055

### ISSUE THREAD

**Issue by irvcaza** [Isela-Saucedo/web_scraping#35]
En el archivo Revista055.csv encontré 3 artículos de presentación que no son artículos reales. 

 Titulo Revista | Area | Tematica | Titulo Articulo | Resumen | Abstract | Link Articulo | Link PDF
 -- | -- | -- | -- | -- | -- | -- | --
Acta Poética | IV. Humanidades y Ciencias de la Conducta | Literatura, Artes, Filosofía y Teoría Crítica | Presentación | Presentación | NaN | https://revistas-filologicas.unam.mx/acta-poet... | https://revistas-filologicas.unam.mx/acta-poet...
Acta Poética | IV. Humanidades y Ciencias de la Conducta | Literatura, Artes, Filosofía y Teoría Crítica | Presentación | Presentación. | NaN | https://revistas-filologicas.unam.mx/acta-poet... | https://revistas-filologicas.unam.mx/acta-poet...
Acta Poética | IV. Humanidades y Ciencias de la Conducta | Literatura, Artes, Filosofía y Teoría Crítica | Presentación | Presentación | NaN | https://revistas-filologicas.unam.mx/acta-poet... | https://revistas-filologicas.unam.mx/acta-poet...

Si pudiéramos eliminarlos

**Comment by Isela-Saucedo** [comment]
Articulos eliminados 310ef2ebdd30a403a47f9f8f1f91f6c2d3562a34

**Comment by irvcaza** [comment]
Como te había compartido en otro comentario, no te recomiendo eliminar utilizando índex. Te recomiendo otra estrategia. Si tienes problemas, me dices para apoyarte con un código de muestra.
