### ISSUE TITLE
Links al Pdf en Revista095

### ISSUE THREAD

**Issue by irvcaza** [Isela-Saucedo/web_scraping#36]
Revisando los archivos Revista095.01.csv Revista095.02.csv Revista095.03.csv Revista095.04.csv se encuentran muchos articulos con el link al PDF

https://www.elsevier.es/es-coronavirus

Revisando los artículos, estos si tienen un enlace al PDF unico. 
Revisando el código al parece que la clase `right` es demasiado general. 
Una solución podría ser buscar ya sea la clase `descargar-pdf` o el texto `Descargar PDF` y buscar el padre de esta etiqueta. Este debe contener el enlace al PDF

**Comment by Isela-Saucedo** [comment]
Modificado 03fb8668f98823af0de20384b71fe0ae9fac4199
