### ISSUE TITLE
Eliminar artículos  Investigación en Educación Médica en revista Revista155

### ISSUE THREAD

**Issue by irvcaza** [Isela-Saucedo/web_scraping#37]
En el archivo Revista155.01.csv estoy encontrando varios artículos con el titulo `Investigación en Educación Médica` el cual hace referencia a la revista. El problema es que uno de ellos si tiene resumen (sin mucho sentido pero tiene algo) por lo que es mejor omitir estos artículos.

También ocurre con el archivo Revista155.02.csv y el título `Noticias y eventos en educación en Ciencias de la Salud`

**Comment by Isela-Saucedo** [comment]
Articulos eliminados dccc506c896cd8f23a155143c047b4337aa49571
