### ISSUE TITLE
Link PDF repetido en Revista213

### ISSUE THREAD

**Issue by irvcaza** [Isela-Saucedo/web_scraping#39]
Revisando el archivo Revista213.csv veo que todos los artículos tienen el mismo link PDF. Al revisar, es una pagina de springer por lo que de cualquier manera el PDF no está disponible abiertamente. Así que bien podría dejarse ese como nulo

**Comment by Isela-Saucedo** [comment]
eliminados 849d4bad32f9169b26f60f0e230cf2f2a3d90cf8
