### ISSUE TITLE
Estandarizar nombre de archivos

### ISSUE THREAD

**Issue by irvcaza** [Isela-Saucedo/web_scraping#6]
Hay que ponerse de acuerdo en como van a nombrar sus archivos para evitar discrepancias.
Actualmente se tienen

- `RevistaXX.YY.csv`
- `RevistXX.YY.csv`

Como puedes notar, la única diferencia es una `a`.
No tengo preferencia por ninguno así que ustedes pueden decidir cual les parece mas conveniente.

En sincronía con https://github.com/JazminTo/web_scraping/issues/1#issue-1311381893

**Comment by irvcaza** [comment]
En la carpeta 20-07-2022 se sigue encontrando diferencias en los nombres de las columnas 

Isela:     ['Titulo Revista', 'Área', 'Temática', 'Titulo Articulo', 'Resumen', 'Abstract', 'Link Articulo', 'Link PDF']
Jazmin: ['Titulo Revista', 'Area', 'Tematica', 'Titulo Articulo', 'Resumen', 'Abstract', 'Link Articulo', 'Link PDF']

**Comment by Isela-Saucedo** [comment]
Modificado en los archivos nuevos 01dc80a
