### ISSUE TITLE
Estandarizar Nombre de columnas

### ISSUE THREAD

**Issue by irvcaza** [Isela-Saucedo/web_scraping#7]
Actualmente, hay discrepancia en el nombre de columnas que cada una les da 

- Isela:    'Titulo de revista', 'Área', 'Temática', 'Titulo del libro', 'Resumen', 'Link inicial', 'Link articulo'
- Jazmin: 'Titulo Revista', 'Area', 'Tematica', 'Titulo Articulo', 'Resumen','Url Inicial', 'Link Articulo'

Es necesario que se pongan de acuerdo y decidan un solo estilo.
Mi recomendación personal sería:

- Que no contengan acentos o caracteres especiales
- Que no incluyan espacios
    - Revisar los distintos estándares de la industria por ejemplo  [Snake case](https://en.wikipedia.org/wiki/Snake_case) y [Camel case](https://en.wikipedia.org/wiki/Camel_case)
- Nombres descriptivos
- Que no rebasen los 30 caracteres de longitud

Estas son solo recomendaciones y no es ninguna regla. Lo mas importante es que sean iguales. 

En sincronía con https://github.com/JazminTo/web_scraping/issues/2#issue-1311407771

**Comment by irvcaza** [comment]
En la carpeta 20-07-2022 se sigue encontrando diferencias en los nombres de las columnas 

Isela:     ['Titulo Revista', 'Área', 'Temática', 'Titulo Articulo', 'Resumen', 'Abstract', 'Link Articulo', 'Link PDF']
Jazmin: ['Titulo Revista', 'Area', 'Tematica', 'Titulo Articulo', 'Resumen', 'Abstract', 'Link Articulo', 'Link PDF']

**Comment by JazminTo** [comment]
Se hicieron las modificacion adecuadas en las columnas.
Titulo Revista', 'Area', 'Tematica', 'Titulo Articulo', 'Resumen', 'Abstract', 'Link Articulo', 'Link PDF'

**Comment by JazminTo** [comment]
Se hicieron las modificacion adecuadas en las columnas.
Titulo Revista', 'Area', 'Tematica', 'Titulo Articulo', 'Resumen', 'Abstract', 'Link Articulo', 'Link PDF'
