### ISSUE TITLE
Metadatos filtrados en artículos 17 y 19 (revisión aleatorea)

### ISSUE THREAD

**Issue by apimentela** [Isela-Saucedo/web_scraping#8]
En la carpeta de salida    se detectaron un par de filtraciones de metadatos:

- Artículo 17.02:
    - La palabra "Resumen" aparece de forma constante como la primer "palabra" dentro de los resúmenes

- Artículo 19.05:
    - La frase "Introducción y objetivos" aparece de forma constante como la primera frase dentro de los resúmenes

**Comment by Isela-Saucedo** [comment]
Modificado 9d261dd104ed22a20ed0c3be7d704c1754113d21
