### ISSUE TITLE
Títulos repetidos 20-07-2022

### ISSUE THREAD

**Issue by irvcaza** [Isela-Saucedo/web_scraping#9]
En la carpeta 20-07-2022 se encontraron los siguientes Títulos repetidos:

- Revista05.csv
    - EFFECT OF MINERAL SUPPLEMENTATION AND TYPE OF STARCH ON THE PRODUCTION OF PRODIGIOSIN FROM A CULTURE OF Serratia marcescens BS303
    - CHARACTERIZATION OF A RESIDUE WITH HIGH ALUMINUM CONTENT
- Revista15.01.csv
    - Covers
    - Dietary resource partitioning in the Late Pleistocene horses from Cedral, north-central Mexico: evidence from the study of dental wear
    - Editorial
- Revista15.03.csv
    - FOREWORD TO THE SPECIAL ISSUE ON THE TECTONIC AND MAGMATIC EVOLUTION OF MEXICO DURING THE CENOZOIC
    - An isotopic study of a late Quaternary loess-paleosol sequence in SW Germany
- Revista21.02.csv
    - Comentarios
    - El crecimiento del empleo y las estrategias laborales de sobrevivencia en México. Apuntes para un debate
    - Bibliografía comentada
- Revista25.csv
    - Preliminares
    - Índice analítico
    - Tabla de casos
    - Revista completa
    - Indicaciones para colaboradores

**Comment by Isela-Saucedo** [comment]
Modificado en la carpeta 27-07-2022
